version: "3.0"
services:
  application:
    image: weather-app:latest
    ports:
      - "3000:3000"
    volumes:
      - ./:/home/node/
    command: "npm run dev"

  jest:
    image: weather-app:latest
    volumes:
      - ./:/home/node/
    command: "npx jest ./__tests__/mongoose/weather/services.test.ts --watchAll"
